spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: coffwok_dev
      authentication-database: admin

app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,http://localhost:5173

  auth:
    tokenSecret: Keanlk192002
    tokenExpirationSec: 864000000

  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

