spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
#   mongodb:
#     host: localhost
#     port: 27017
#     database: coffwok_dev
#     authentication-database: admin
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

  servlet:
    multipart:
      max-file-size: ${SERVLET_MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${SERVLET_MULTIPART_MAX_REQUEST_SIZE}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI}
            scope:
              - ${SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE}

app:
  cors:
    allowedOrigins: ${APP_CORS_ALLOWED_ORIGINS}

  auth:
    tokenSecret: ${APP_AUTH_TOKEN_SECRET}
    tokenExpirationSec: ${APP_AUTH_TOKEN_EXPIRATION_SEC}

  oauth2:
    authorizedRedirectUris:
      - ${APP_OAUTH2_AUTHORIZED_REDIRECT_URIS}
