spring:
  data:
    mongodb:
      uri: mongodb+srv://Cluster46068:Keanlk192002@cluster46068.xxm5ube.mongodb.net/?retryWrites=true&w=majority
      database: coffwok_dev
#    mongodb:
#      host: localhost
#      port: 27017
#      database: coffwok_dev
#      authentication-database: admin

  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 16617165058-nci3drur9g8dkd7ij6iv9b197dqomam9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,http://localhost:5173

  auth:
    tokenSecret: Keanlk192002
    tokenExpirationSec: 5184000000

  oauth2:
    authorizedRedirectUris:
      - http://localhost:5173/oauth2/redirect

